services:
  # BACKEND (Laravel)
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: smartqueue_php
    working_dir: /var/www/html/backend
    volumes:
      - ./backend:/var/www/html/backend
      - /var/www/html/backend/vendor #
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
    networks:
      - smartqueue_network

      # QUEUE WORKER (Real-time Engine)
  php-worker:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: smartqueue_worker
    working_dir: /var/www/html/backend
    restart: always
    volumes:
      - ./backend:/var/www/html/backend
      - vendor_data:/var/www/html/backend/vendor
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    # This is the magic command that replaces your manual terminal
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - smartqueue_network

# REDIS (The missing piece for your WebSockets)
  redis:
    image: redis:alpine
    container_name: smartqueue_redis
    ports:
      - "6379:6379"
    networks:
      - smartqueue_network

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: smartqueue_ws
    ports:
      - "3000:3000"
    # ADD THIS SECTION:
    env_file:
      - ./backend/.env # This tells Docker to inject your .env variables into the container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - smartqueue_network

   # SCHEDULER (Laravel scheduled tasks)
  scheduler:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: smartqueue_scheduler
    working_dir: /var/www/html/backend
    restart: always
    volumes:
      - ./backend:/var/www/html/backend
      - vendor_data:/var/www/html/backend/vendor
    command: php artisan schedule:work
    depends_on:
      - php
      - mysql
    networks:
      - smartqueue_network


  # NGINX (Routing for Backend and Admin Web)
  nginx:
    image: nginx:alpine
    container_name: smartqueue_nginx
    ports:
      - "8090:80"    # Backend API
    
    volumes:
      - ./backend:/var/www/html/backend
      - ./admin-web:/var/www/html/admin-web
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - smartqueue_network


  mysql:
    image: mysql:8.0
    container_name: smartqueue_db
    restart: unless-stopped
    ports:
      - "33069:3306"
    environment:
      MYSQL_DATABASE: smart_queue_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smartqueue_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartqueue_pma
    ports:
      - "8091:80"
    environment:
      PMA_HOST: mysql
    networks:
      - smartqueue_network

volumes:
  mysql_data:
  vendor_data:

networks:
  smartqueue_network:
    driver: bridge